### ISSUE TITLE
alpn-boot 8.1.7.v20160121 released for 1.8.0u72

### ISSUE THREAD

**Issue by Scottmitch** [trustin/jetty-alpn-agent#1]
Builds break if using jdk 1.8.0u72 because of class incompatibilities. The plugin should be updated to support the new alpn-boot version alpn-boot 8.1.7.v20160121.

See www.eclipse.org/jetty/documentation/current/alpn-chapter.html

**Comment by Scottmitch** [comment]
@trustin /cc

**Comment by trustin** [comment]
Just released 1.0.1.Final with the support for 8u71/72.

**Comment by Scottmitch** [comment]
Thanks @trustin !

**Comment by vietj** [comment]
:+1:
