### ISSUE TITLE
Move this plugin into Netty

### ISSUE THREAD

**Issue by Scottmitch** [trustin/jetty-alpn-agent#2]
Netty previously had control of the versioning of alpn-boot and npn-boot. This project moves the maintenance outside of the control of the Netty project and makes maintenance a bit more complicated. Is it possible to move this plugin into the Netty project?

**Comment by Scottmitch** [comment]
@normanmaurer @trustin - /cc

**Comment by Scottmitch** [comment]
@nmittler - FYI

**Comment by nmittler** [comment]
@Scottmitch why don't we just deprecate the usage of jetty-alpn in favor of tcnative?

**Comment by Scottmitch** [comment]
@nmittler - We still have code that depends upon it and that we need to test. Also users maybe unable/unwilling to use tcnative in some cases?

**Comment by trustin** [comment]
@Scottmitch Sure, I'm fine with moving this into Netty. I just created it personally because I wasn't sure if it should be part of Netty. Alternatively, Jetty community could take this over? /cc @gregw

**Comment by gregw** [comment]
@trustin Not keen to take on more maintenance, as we have enough on our plate.   However, if somebody wanted to contribute something to the alpn project that makes it simple to consume or handle the maintenance issues, then we'd definitely look at that.

**Comment by Scottmitch** [comment]
The maintenance is relatively low, just need a small update to include new versions when they are released.  See https://github.com/trustin/jetty-alpn-agent/commit/9b54650f8f8018451978b8d49987bbc411d15e04 for an example (1 line change and include the new jar file).

**Comment by trustin** [comment]
I can move this to netty if Jetty folks are uninterested. Opinions?

**Comment by trustin** [comment]
We can also think about moving the os-maven-plugin to Netty as well.

**Comment by Scottmitch** [comment]
If Jetty folks are uninterested then I'm in favor of moving to Netty.

**Comment by gregw** [comment]
Let me double check if we are interested or not.   Will get back in 24
hours.

On 10 February 2016 at 05:00, Scott Mitchell notifications@github.com
wrote:

> If Jetty folks are uninterested then I'm in favor of moving to Netty.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/trustin/jetty-alpn-agent/issues/2#issuecomment-182186566
> .

## 

Greg Wilkins gregw@webtide.com CTO http://webtide.com

**Comment by trustin** [comment]
Thanks, @gregw!

**Comment by sbordet** [comment]
Guys, the Jetty project can take this over.

The license is AL2 so it's good, the repo name is good, we could just [transfer the repo](https://help.github.com/articles/transferring-a-repository/) to the https://github.com/jetty-project organization.

Thoughts ?

**Comment by trustin** [comment]
@sbordet Awesome. Thank you very much, guys. Let me transfer this real soon.

**Comment by trustin** [comment]
@sbordet I transferred the ownership to jetty-project. Let me know if it worked.

**Comment by sbordet** [comment]
@trustin I don't see it under the jetty-project organization.
Are you sure the transfer went ok ? Or perhaps it takes time to be moved ?

**Comment by trustin** [comment]
@sbordet I guess I do not have proper permission on the jetty-project organization. Could you add me to the admin list there?

> On the other end, the person transferring the repository also needs to have owner or admin rights in the receiving organization.

**Comment by sbordet** [comment]
@trustin can we do the opposite ? You make me an owner of this repo only, and I'll do the transfer. Thanks !

**Comment by trustin** [comment]
@sbordet It seems like there's no way to make someone an admin of a personal repo. I think I can transfer this repo to your personal account without restriction though. Will you transfer then?

**Comment by sbordet** [comment]
@trustin, sure, let's try that.

**Comment by trustin** [comment]
@sbordet Transfer request has been sent to you. Please accept and complete the transfer to jetty-project.

**Comment by sbordet** [comment]
@trustin, it's transferred and you have write access to the repository. Thanks !

**Comment by sbordet** [comment]
@trustin, are you ok with moving the package names from `kr.motd.` to `org.mortbay.jetty` (like ALPN and NPN boot jars are), updating it for JDK 8u74, and then releasing version 2.0.0 ?

**Comment by trustin** [comment]
@sbordet Sure. No problem. Could you leave some credits somewhere like in README.md though?

**Comment by sbordet** [comment]
@trustin project was imported, package updated, released 2.0.0 without changes just to make sure that the process works. I tested it locally, works for me. Added credits to README. I think we are done, let me know if you want something changed (well, you still have commit rights, so ;)

**Comment by Scottmitch** [comment]
@sbordet - Thanks for taking this over! I hope it helps :)
